### ISSUE TITLE
Incompatible with x64 Windows 11

### ISSUE THREAD

**Issue by elrod829** [komh/kmididec#8]
Attempting to launch through the terminal results in this:

_`Program 'kmidi.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1 + .\kmidi.exe + ~~~~~~~~~~~. At line:1 char:1 + .\kmidi.exe + ~~~~~~~~~~~ + CategoryInfo : ResourceUnavailable: (:) [], ApplicationFailedException + FullyQualifiedErrorId : NativeCommandFailed`_

I'm running Windows 11 Version 10.0.22631 Build 22631 on an ASUS Vivobook X513EAN-K513EA laptop with an Intel i7-1165G7 CPU.

**Comment by komh** [comment]
Hi/2.

I'm sorry that pre-built ```kmidi.exe``` is for OS/2 only. It cannot be executed on other OSes. If you want, you should port it first.
